# You may need to change this line for your real project.
baseURL: /

languageCode: en-us
defaultContentLanguage: en

# Keep title short to prevent overflow.
# There’s no official guidance on this, but 40 characters for
# mobile and 60 for desktop is roughly the sweet spot.
#
# NB: Final title of shareable pages will be this plus the
#     title of the page. Eg. "Contacts - Ed."
title: Rahul Arasikere

# Use full path to theme's repository in case of using Hugo Modules.
# This is replaced in go.mod for exampleSite to point to the directory above.
theme: github.com/barklan/hugo-dead-simple


enableRobotsTXT: true

# When using ref or relref to resolve page links and a link cannot
# resolved, it will be logged with this log level.
refLinksErrorLevel: WARNING

# We have just the default tags taxonomy, and remove the categories
# taxonomy for site as not used.
taxonomies:
  tag: tags

# Google Analytics Tracking ID.
#
# For more info, read the article
# https://support.google.com/analytics/answer/10089681
#
# Set `HUGO_ENV` environment variable or `site.Params.env` configuration
# parameter to "production" to use Google Analytics.
googleAnalytics: ''

minify:
  # Do not minify XML files to avoid CDATA escape issues
  disableXML: true
  tdewolff:
    html:
      keepQuotes: true

mediaTypes:
  text/xml:
    suffixes:
      - xml
  application/feed+json:
    suffixes:
      - json
  application/manifest+json:
    suffixes:
      - webmanifest

# Sitemap config
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

author:
  name: Rahul Arasikere
  email: arasikere.rahul@gmail.com
  github: rahul_arasikere
  location: 'Boston, Massachusetts.'

# For more see https://gohugo.io/getting-started/configuration-markup/
markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

# If enableGitInfo is true, it will override any lastmod dates in our
# front matter. We should at least allow ourselves to manually override
# this value in the front matter.
frontmatter:
  lastmod:
    - lastmod
    - ':git'
    - date
    - publishDate

module:
  hugoVersion:
    extended: true
    min: '0.95.0'
  imports:
    - path: github.com/barklan/hugo-dead-simple

