# For more see https://gohugo.io/content-management/menus/

main:                # sections in the website sidebar
  - identifier: home # section id
    name: home       # section display title
    url: /           # path to the section
    weight: 1        # order of sections

  - identifier: about
    name: about
    url: /about/
    weight: 2

  - identifier: tags
    name: tags
    url: /tags/
    weight: 5

  - identifier: github
    name: github_profile
    url: 'https://github.com/rahul-arasikere/'
    weight: 20
    params:
      external: true

