# Site description. Used in meta description
description: >-
  Rahul Arasikere's personal blog.

# SEO keywords. Used in 'meta name="keywords"' tag.
# May be overridden by .Keywords or .Tags in front matter.
keywords:
  - rahul
  - arasikere
  - embedded
  - boston

# A "copyright"-line to be added to RSS/Atom files.
# "&copy;" and "{year}" will be replaced by © and the current year.
copyright: 'Copyright &copy; 2023-{year} Rahul Arasikere'

# Colour scheme. Options: red, orange, magenta, cyan, blue, brown
colorScheme: 'red'

# Used in site header
tagline: an embedded engineer currently working in Boston.

# Custom footer text on left sidebar. Use HTMl if needed.
# "&copy;" and "{year}" will be replaced by © and the current year.
footer: >-
  Built with <a href="https://github.com/sergeyklay/gohugo-theme-ed"
  target="_blank" rel="noopener noreferrer">Ed</a>. Distributed under an MIT
  license.

# Posts date format, for example: 2006-01-02
dateFormat: ':date_long'
dateFormatToc: 2006.01.02


# Site icons, relative to ./static
assets:
  # favicon.ico for legacy browsers
  favicon: ''

  # A single SVG icon with a light/dark version for modern browsers
  svgicon: ''

  # 180×180 PNG image for Apple devices
  apple_touch_icon: ''

  # Logo image, relative to ./assets
  logo: /img/logo.jpg
  disable_fingerprinting: false

seo:
  # Will be used in schema.org/Organization.
  # The site.Title  will be used if empty.
  publisher: Rahul Arasikere

  # To anonymize the IP addresses of hits sent to Google Analytics
  # set this param to true. Please note, to enable Google Analytics
  # you have to set `googleAnalytics` param in config.yaml file.
  anonymizeIp: true

social:
  # Array of Facebook Page Admin IDs for Domain Insights
  facebookAdminIds: []

  # Facebook Page ID
  facebookId: ''

  # Twitter username for the website
  twitter: ''

# Configure search engine
search:
  # Maximum length (in words) of each text blurb. You can change this
  # value if you find that 100 is too short or too long for your taste.
  maxSummaryLength: 100
  # Lunr has full support for the indexing and searching of documents
  # in English. If your documents are in another language, uncomment
  # required languages below.
  #
  # For more see: https://lunrjs.com/guides/language_support.html
  languages:
    # - de
    - en
    # - es
    # - fr
    # - it
    # - pt
    # - ru
